-- Merges real rounds from the BF2Statistics database into the session log.
-- * 19 existing rows (spreadsheet + admin entries) are matched to a real round on
--   map, player count and result; they keep their size and difficulty and gain the
--   real date (US Eastern) and a link to the stats round; their bot count is kept.
-- * The remaining 3-6 player rounds are inserted new. Size follows your play pattern:
--   3-4 players = smallest size the map has, 5-6 players = 64, Urban Decay/Urban Jungle = 32, City District 5-6p = 32.
-- * The 3-player Falklands win is moved from size 16 to 32 (Falklands has no 16).
-- * Rounds with 1-2 or 7+ human players are not imported (the site models 3-6).
-- Safe to re-run. Run after 003_map_size_data.sql and 004_allow_null_played_at.sql.

alter table public.bf2_game_logs add column if not exists stats_round_id bigint unique;

-- Link existing rows to their real round
update public.bf2_game_logs set played_at = '2025-05-08', stats_round_id = 11, notes = 'Date from stats round #11 (size, bots and difficulty from spreadsheet)' where id = 'bdaae828-3584-45e8-989a-96c3aaba7c40' and stats_round_id is null;  -- Devil's Perch 3p win
update public.bf2_game_logs set played_at = '2025-06-05', stats_round_id = 32, notes = 'Date from stats round #32 (size, bots and difficulty from spreadsheet)' where id = 'a5f23d22-f58b-4ed5-9fd6-173a54d3203d' and stats_round_id is null;  -- Trident 3p win
update public.bf2_game_logs set played_at = '2025-06-26', stats_round_id = 44, notes = 'Date from stats round #44 (size, bots and difficulty from spreadsheet)' where id = 'cb885a8f-55fd-4287-8103-a6a0c8b4d1dc' and stats_round_id is null;  -- Daliant Plant 4p win
update public.bf2_game_logs set played_at = '2025-06-29', stats_round_id = 49, notes = 'Date from stats round #49 (size, bots and difficulty from spreadsheet)' where id = 'd08c5e5c-f82f-4a94-9a5c-7f9a3e3fb902' and stats_round_id is null;  -- Falklands 3p win
update public.bf2_game_logs set played_at = '2025-06-29', stats_round_id = 51, notes = 'Date from stats round #51 (size, bots and difficulty from spreadsheet)' where id = '1e23c11c-997a-45b7-89e7-f898b193397b' and stats_round_id is null;  -- Greasy Mullet 3p win
update public.bf2_game_logs set played_at = '2025-07-04', stats_round_id = 54, notes = 'Date from stats round #54 (size, bots and difficulty from spreadsheet)' where id = 'f47cba71-5005-4803-9ea8-d6bbf88705fb' and stats_round_id is null;  -- Static 3p win
update public.bf2_game_logs set played_at = '2025-08-14', stats_round_id = 84, notes = 'Date from stats round #84 (size, bots and difficulty from spreadsheet)' where id = '0f99525a-5218-4baf-ab47-4366c8a061f6' and stats_round_id is null;  -- Daqing Oilfields 3p win
update public.bf2_game_logs set played_at = '2025-11-13', stats_round_id = 90, notes = 'Date from stats round #90 (size, bots and difficulty from spreadsheet)' where id = 'bec7d999-5c02-4246-a98d-1092b166a2fd' and stats_round_id is null;  -- Kubra Dam 6p win
update public.bf2_game_logs set played_at = '2025-11-13', stats_round_id = 91, notes = 'Date from stats round #91 (size, bots and difficulty from spreadsheet)' where id = '84880309-c95e-4006-9581-9a3ce8332963' and stats_round_id is null;  -- Karkand Storm 5p win
update public.bf2_game_logs set played_at = '2025-11-13', stats_round_id = 92, notes = 'Date from stats round #92 (size, bots and difficulty from spreadsheet)' where id = '7732f834-a1e3-42d8-87b0-f24c9c30a39c' and stats_round_id is null;  -- Road to Jalalabad 4p loss
update public.bf2_game_logs set played_at = '2025-11-14', stats_round_id = 93, notes = 'Date from stats round #93 (size, bots and difficulty from spreadsheet)' where id = '657957bd-d33c-4c9a-983d-a307e8ddf9e7' and stats_round_id is null;  -- Road to Jalalabad 4p loss
update public.bf2_game_logs set played_at = '2026-01-29', stats_round_id = 95, notes = 'Date from stats round #95 (size, bots and difficulty from spreadsheet)' where id = '52e801a2-7532-4872-b26c-8e565bf054fa' and stats_round_id is null;  -- Static 4p win
update public.bf2_game_logs set played_at = '2026-03-24', stats_round_id = 97, notes = 'Date from stats round #97 (size, bots and difficulty from spreadsheet)' where id = 'da11db0e-cabc-4be5-bda1-763a133a54fc' and stats_round_id is null;  -- Devil's Perch 4p win
update public.bf2_game_logs set played_at = '2026-03-24', stats_round_id = 98, notes = 'Date from stats round #98 (size, bots and difficulty from spreadsheet)' where id = '33e76d71-b731-41a1-bf2c-1437a263e3bf' and stats_round_id is null;  -- Damocles 3p win
update public.bf2_game_logs set played_at = '2026-03-24', stats_round_id = 99, notes = 'Date from stats round #99 (size, bots and difficulty from spreadsheet)' where id = 'd6f5705c-0e93-4461-b773-caa522cf9271' and stats_round_id is null;  -- Wake Island 3p win
update public.bf2_game_logs set played_at = '2026-09-17', stats_round_id = 101, notes = 'Date from stats round #101' where id = 'a199b652-5514-493f-a367-fa14fd3a3e4f' and stats_round_id is null;  -- Hammer down 3p win
update public.bf2_game_logs set played_at = '2026-09-17', stats_round_id = 102, notes = 'Date from stats round #102' where id = '3a35a16a-2608-4b6e-b8c0-0cdd98716327' and stats_round_id is null;  -- Karkand Storm 3p loss
update public.bf2_game_logs set played_at = '2026-09-17', stats_round_id = 103, notes = 'Date from stats round #103' where id = 'c3a36aa3-d433-40d5-8517-60d755e2f063' and stats_round_id is null;  -- Karkand Storm 4p win
update public.bf2_game_logs set played_at = '2026-09-17', stats_round_id = 104, notes = 'Date from stats round #104' where id = '6963e208-4814-4080-87fa-68af7ab98f38' and stats_round_id is null;  -- Dragon Valley 3p win

-- Falklands has no size 16 (32 and 64 only); the spreadsheet logged this 3-player win at 16.
update public.bf2_game_logs set map_size = 32 where id = 'd08c5e5c-f82f-4a94-9a5c-7f9a3e3fb902' and map_size = 16;

-- Insert rounds that were not in the spreadsheet
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 19), 6, 64, 50, 'win', null, '2025-05-08', 'Imported from stats round #5 (size assumed)', 5) on conflict (stats_round_id) do nothing;  -- gulf_of_oman
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 10), 6, 32, 60, 'loss', null, '2025-05-08', 'Imported from stats round #9 (size assumed)', 9) on conflict (stats_round_id) do nothing;  -- city_district
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 58), 5, 64, 40, 'loss', null, '2025-05-22', 'Imported from stats round #12 (size assumed)', 12) on conflict (stats_round_id) do nothing;  -- wake_twilight
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 19), 6, 64, 70, 'win', null, '2025-05-22', 'Imported from stats round #17 (size assumed)', 17) on conflict (stats_round_id) do nothing;  -- gulf_of_oman
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 47), 3, 16, 30, 'loss', null, '2025-05-28', 'Imported from stats round #20 (size assumed)', 20) on conflict (stats_round_id) do nothing;  -- tng_street
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 47), 4, 16, 49, 'win', null, '2025-05-28', 'Imported from stats round #21 (size assumed)', 21) on conflict (stats_round_id) do nothing;  -- tng_street
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 25), 5, 64, 60, 'win', null, '2025-05-28', 'Imported from stats round #22 (size assumed)', 22) on conflict (stats_round_id) do nothing;  -- night_flight
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 12), 5, 64, 60, 'win', null, '2025-05-28', 'Imported from stats round #23 (size assumed)', 23) on conflict (stats_round_id) do nothing;  -- daqing_dawn
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 38), 6, 64, 70, 'win', null, '2025-06-05', 'Imported from stats round #31 (size assumed)', 31) on conflict (stats_round_id) do nothing;  -- tng_fushe_pass
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 23), 5, 64, 30, 'win', null, '2025-06-12', 'Imported from stats round #33 (size assumed)', 33) on conflict (stats_round_id) do nothing;  -- mass_destruction
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 37), 6, 64, 60, 'loss', null, '2025-06-12', 'Imported from stats round #34 (size assumed)', 34) on conflict (stats_round_id) do nothing;  -- tng_course_of_the_river
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 27), 4, 16, 25, 'win', null, '2025-06-19', 'Imported from stats round #35 (size assumed)', 35) on conflict (stats_round_id) do nothing;  -- road_to_jalalabad
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 29), 5, 64, 50, 'loss', null, '2025-06-19', 'Imported from stats round #36 (size assumed)', 36) on conflict (stats_round_id) do nothing;  -- sf_op_harvest
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 29), 5, 64, 50, 'win', null, '2025-06-19', 'Imported from stats round #37 (size assumed)', 37) on conflict (stats_round_id) do nothing;  -- sf_op_harvest
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 5), 5, 64, 50, 'win', null, '2025-06-19', 'Imported from stats round #38 (size assumed)', 38) on conflict (stats_round_id) do nothing;  -- aix_operation_static
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 5), 5, 64, 71, 'loss', null, '2025-06-19', 'Imported from stats round #39 (size assumed)', 39) on conflict (stats_round_id) do nothing;  -- aix_operation_static
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 31), 5, 64, 50, 'win', null, '2025-06-19', 'Imported from stats round #40 (size assumed)', 40) on conflict (stats_round_id) do nothing;  -- sf_smoke_screen
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 15), 5, 64, 50, 'loss', null, '2025-06-19', 'Imported from stats round #41 (size assumed)', 41) on conflict (stats_round_id) do nothing;  -- dragon_valley_moon
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 15), 5, 64, 50, 'win', null, '2025-06-19', 'Imported from stats round #42 (size assumed)', 42) on conflict (stats_round_id) do nothing;  -- dragon_valley_moon
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 11), 4, 16, 28, 'loss', null, '2025-06-26', 'Imported from stats round #43 (size assumed)', 43) on conflict (stats_round_id) do nothing;  -- dalian_plant
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 59), 3, 16, 20, 'win', null, '2025-06-28', 'Imported from stats round #48 (size assumed)', 48) on conflict (stats_round_id) do nothing;  -- warlord
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 3), 3, 16, 25, 'loss', null, '2025-06-29', 'Imported from stats round #50 (size assumed)', 50) on conflict (stats_round_id) do nothing;  -- aix_greasy_mullet
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 47), 3, 16, 30, 'win', null, '2025-06-29', 'Imported from stats round #52 (size assumed)', 52) on conflict (stats_round_id) do nothing;  -- tng_street
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 50), 4, 64, 40, 'win', null, '2025-07-03', 'Imported from stats round #53 (size assumed)', 53) on conflict (stats_round_id) do nothing;  -- tng_town_strike
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 26), 6, 64, 40, 'win', null, '2025-07-10', 'Imported from stats round #59 (size assumed)', 59) on conflict (stats_round_id) do nothing;  -- processing_plant
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 46), 6, 64, 40, 'loss', null, '2025-07-10', 'Imported from stats round #60 (size assumed)', 60) on conflict (stats_round_id) do nothing;  -- tng_sands_of_sinai
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 46), 3, 64, 10, 'win', null, '2025-07-10', 'Imported from stats round #61 (size assumed)', 61) on conflict (stats_round_id) do nothing;  -- tng_sands_of_sinai
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 19), 4, 16, 30, 'win', null, '2025-07-10', 'Imported from stats round #62 (size assumed)', 62) on conflict (stats_round_id) do nothing;  -- gulf_of_oman
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 60), 5, 64, 40, 'win', null, '2025-07-17', 'Imported from stats round #65 (size assumed)', 65) on conflict (stats_round_id) do nothing;  -- zatar_wetlands_ii
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 33), 6, 64, 60, 'loss', null, '2025-07-17', 'Imported from stats round #66 (size assumed)', 66) on conflict (stats_round_id) do nothing;  -- sharqi_peninsula
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 33), 6, 64, 50, 'win', null, '2025-07-17', 'Imported from stats round #67 (size assumed)', 67) on conflict (stats_round_id) do nothing;  -- sharqi_peninsula
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 33), 6, 64, 50, 'win', null, '2025-07-17', 'Imported from stats round #68 (size assumed)', 68) on conflict (stats_round_id) do nothing;  -- sharqi_peninsula
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 36), 4, 16, 40, 'win', null, '2025-07-17', 'Imported from stats round #69 (size assumed)', 69) on conflict (stats_round_id) do nothing;  -- tng_clean_sweep_ii
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 38), 5, 64, 40, 'win', null, '2025-07-31', 'Imported from stats round #73 (size assumed)', 73) on conflict (stats_round_id) do nothing;  -- tng_fushe_pass
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 46), 6, 64, 30, 'win', null, '2025-07-31', 'Imported from stats round #74 (size assumed)', 74) on conflict (stats_round_id) do nothing;  -- tng_sands_of_sinai
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 35), 4, 32, 40, 'win', null, '2025-07-31', 'Imported from stats round #75 (size assumed)', 75) on conflict (stats_round_id) do nothing;  -- tng_airport
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 31), 4, 16, 40, 'win', null, '2025-07-31', 'Imported from stats round #76 (size assumed)', 76) on conflict (stats_round_id) do nothing;  -- sf_smoke_screen
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 11), 5, 64, 40, 'win', null, '2025-08-07', 'Imported from stats round #77 (size assumed)', 77) on conflict (stats_round_id) do nothing;  -- dalian_plant
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 13), 5, 64, 60, 'win', null, '2025-08-07', 'Imported from stats round #78 (size assumed)', 78) on conflict (stats_round_id) do nothing;  -- devils_perch
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 18), 4, 16, 45, 'loss', null, '2025-08-07', 'Imported from stats round #79 (size assumed)', 79) on conflict (stats_round_id) do nothing;  -- greatwall
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 18), 4, 16, 45, 'loss', null, '2025-08-07', 'Imported from stats round #80 (size assumed)', 80) on conflict (stats_round_id) do nothing;  -- greatwall
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 18), 5, 64, 45, 'win', null, '2025-08-07', 'Imported from stats round #81 (size assumed)', 81) on conflict (stats_round_id) do nothing;  -- greatwall
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 56), 4, 32, 40, 'win', null, '2025-08-14', 'Imported from stats round #85 (size assumed)', 85) on conflict (stats_round_id) do nothing;  -- urban_decay
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 47), 3, 16, 30, 'win', null, '2025-08-14', 'Imported from stats round #86 (size assumed)', 86) on conflict (stats_round_id) do nothing;  -- tng_street
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 34), 3, 64, 40, 'win', null, '2025-08-14', 'Imported from stats round #87 (size assumed)', 87) on conflict (stats_round_id) do nothing;  -- the_push_day
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 34), 4, 64, 60, 'win', null, '2025-08-14', 'Imported from stats round #88 (size assumed)', 88) on conflict (stats_round_id) do nothing;  -- the_push_day
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 14), 5, 64, 60, 'win', null, '2025-08-14', 'Imported from stats round #89 (size assumed)', 89) on conflict (stats_round_id) do nothing;  -- dragon_valley
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 18), 4, 16, 30, 'win', null, '2026-01-29', 'Imported from stats round #94 (size assumed)', 94) on conflict (stats_round_id) do nothing;  -- greatwall
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 11), 4, 16, 40, 'loss', null, '2026-01-29', 'Imported from stats round #96 (size assumed)', 96) on conflict (stats_round_id) do nothing;  -- dalian_plant
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 8), 3, 16, 30, 'win', null, '2026-03-24', 'Imported from stats round #100 (size assumed)', 100) on conflict (stats_round_id) do nothing;  -- aix_trident
