-- Rounds from the stats dump bf2stats_2026_9-18.
-- * Rounds matching a session you logged by hand get the real date and a link to the
--   stats round; that session keeps its size, bots and difficulty.
-- * The other 3-8 player rounds are inserted new. Size is inferred (see scripts/bf2stats_config.py),
--   difficulty is left blank: fill it in with Edit in admin.
-- Safe to re-run (each round is linked by stats_round_id and only ever imported once).

alter table public.bf2_game_logs add column if not exists stats_round_id bigint unique;

-- New rounds
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 12), 7, 64, 60, 'win', null, '2025-05-01', 'Imported from stats round #2 (size assumed)', 2) on conflict (stats_round_id) do nothing;  -- daqing_dawn
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 9), 7, 64, 60, 'win', null, '2025-05-01', 'Imported from stats round #3 (size assumed)', 3) on conflict (stats_round_id) do nothing;  -- aix_wake_island_2007
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 28), 7, 64, 60, 'win', null, '2025-05-01', 'Imported from stats round #4 (size assumed)', 4) on conflict (stats_round_id) do nothing;  -- sf_midnight_sun
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 21), 7, 64, 50, 'win', null, '2025-05-08', 'Imported from stats round #6 (size assumed)', 6) on conflict (stats_round_id) do nothing;  -- karkand_stormfront
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 14), 7, 64, 65, 'win', null, '2025-05-08', 'Imported from stats round #7 (size assumed)', 7) on conflict (stats_round_id) do nothing;  -- dragon_valley
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 11), 7, 64, 65, 'loss', null, '2025-05-08', 'Imported from stats round #8 (size assumed)', 8) on conflict (stats_round_id) do nothing;  -- dalian_plant
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 10), 7, 32, 60, 'win', null, '2025-05-08', 'Imported from stats round #10 (size assumed)', 10) on conflict (stats_round_id) do nothing;  -- city_district
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 30), 7, 64, 70, 'win', null, '2025-05-22', 'Imported from stats round #13 (size assumed)', 13) on conflict (stats_round_id) do nothing;  -- sf_road_rage
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 57), 8, 32, 80, 'loss', null, '2025-05-22', 'Imported from stats round #14 (size assumed)', 14) on conflict (stats_round_id) do nothing;  -- urban_jungle
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 57), 8, 32, 116, 'loss', null, '2025-05-22', 'Imported from stats round #15 (size assumed)', 15) on conflict (stats_round_id) do nothing;  -- urban_jungle
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 57), 8, 32, 115, 'win', null, '2025-05-22', 'Imported from stats round #16 (size assumed)', 16) on conflict (stats_round_id) do nothing;  -- urban_jungle
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 1), 7, 64, 50, 'win', null, '2025-06-05', 'Imported from stats round #28 (size assumed)', 28) on conflict (stats_round_id) do nothing;  -- aix_archipelago
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 7), 7, 64, 60, 'win', null, '2025-06-05', 'Imported from stats round #29 (size assumed)', 29) on conflict (stats_round_id) do nothing;  -- aix_sf_surge
insert into public.bf2_game_logs (map_id, player_count, map_size, bot_count, result, difficulty, played_at, notes, stats_round_id) values ((select id from public.bf2_maps where sort_order = 8), 8, 64, 40, 'win', null, '2025-06-26', 'Imported from stats round #45 (size assumed)', 45) on conflict (stats_round_id) do nothing;  -- aix_trident
