#!/usr/bin/env python3
"""Turn a BF2Statistics MySQL dump (.frm/.MYD/.MYI files) into Supabase SQL.

Usage: python3 scripts/bf2stats_to_sql.py data/bf2stats_2026_9-18

Loads a copy of the files into a throwaway MariaDB container (Docker required),
so the originals are never modified, then writes supabase/008_import_players.sql.
Player IP addresses are never read or exported.
"""
import os
import shutil
import subprocess
import sys
import tempfile
import time

CONTAINER = "bf2stats_import"
ROOT_PW = "bf2pass"
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "supabase")


def sh(*args, check=True, **kw):
    return subprocess.run(args, check=check, capture_output=True, text=True, **kw)


def query(sql):
    out = sh(
        "docker", "exec", CONTAINER, "mariadb", "-uroot", f"-p{ROOT_PW}",
        "--default-character-set=utf8mb4", "--batch", "--raw", "-N", "-e", sql,
    ).stdout
    return [line.split("\t") for line in out.splitlines() if line]


def lit(value):
    return "'" + value.replace("'", "''") + "'"


def int_or_null(value):
    return "null" if value in ("", "NULL", "0") else value


def main(data_dir):
    if not os.path.isdir(data_dir):
        sys.exit(f"Not a folder: {data_dir}")

    sh("docker", "rm", "-f", CONTAINER, check=False)
    sh("docker", "run", "-d", "--name", CONTAINER,
       "-e", f"MARIADB_ROOT_PASSWORD={ROOT_PW}", "mariadb:10.11")
    try:
        for _ in range(60):
            if sh("docker", "exec", CONTAINER, "mariadb", "-uroot", f"-p{ROOT_PW}",
                  "-e", "select 1", check=False).returncode == 0:
                break
            time.sleep(2)
        else:
            sys.exit("MariaDB did not start in time.")

        query("CREATE DATABASE bf2stats DEFAULT CHARACTER SET latin1")
        with tempfile.TemporaryDirectory() as tmp:
            for name in os.listdir(data_dir):
                shutil.copy(os.path.join(data_dir, name), tmp)
            sh("docker", "cp", tmp + "/.", f"{CONTAINER}:/var/lib/mysql/bf2stats/")
        sh("docker", "exec", "-u", "root", CONTAINER, "chown", "-R", "mysql:mysql",
           "/var/lib/mysql/bf2stats")
        query("FLUSH TABLES")

        players = query(
            "SELECT id, TRIM(name), country, score, rounds, wins, losses, kills, deaths, "
            "time, lastonline FROM bf2stats.player WHERE rounds > 0 ORDER BY score DESC"
        )
    finally:
        sh("docker", "rm", "-f", CONTAINER, check=False)

    lines = [
        "-- Player standings imported from a BF2Statistics database dump.",
        f"-- Source folder: {os.path.basename(os.path.normpath(data_dir))}",
        "-- Generated by scripts/bf2stats_to_sql.py; safe to re-run (upserts on external_id).",
        "-- Run after 007_players.sql. IP addresses are not included.",
        "",
        "insert into public.bf2_players",
        "  (external_id, name, score, rounds, wins, losses, kills, deaths, play_seconds, country, last_online)",
        "values",
    ]
    rows = []
    for pid, name, country, score, rounds, wins, losses, kills, deaths, secs, last in players:
        last_sql = f"to_timestamp({last})" if last not in ("", "0") else "null"
        country_sql = lit(country.lower()) if country else "null"
        rows.append(
            f"  ({pid}, {lit(name)}, {score}, {rounds}, {wins}, {losses}, {kills}, {deaths}, "
            f"{secs}, {country_sql}, {last_sql})"
        )
    lines.append(",\n".join(rows))
    lines += [
        "on conflict (external_id) do update set",
        "  name = excluded.name,",
        "  score = excluded.score,",
        "  rounds = excluded.rounds,",
        "  wins = excluded.wins,",
        "  losses = excluded.losses,",
        "  kills = excluded.kills,",
        "  deaths = excluded.deaths,",
        "  play_seconds = excluded.play_seconds,",
        "  country = excluded.country,",
        "  last_online = excluded.last_online;",
        "",
    ]

    out_path = os.path.normpath(os.path.join(OUT_DIR, "008_import_players.sql"))
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {len(rows)} players to {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
